@rootAPI = http://localhost:8000/api/v1


# ====== admin api 
### Creare new admin
POST {{rootAPI}}/admin
Content-Type: application/json

{
"fName" : "Prem",
"lName": "Acharya",
"phone": "042345",
"password": "ff",
"email": "a@a.com",
"address": ""
} 

### Loginadmin
POST {{rootAPI}}/admin/sign-in
Content-Type: application/json

{
"email": "a@a.com",
"password": "123456"
}




# ====== admin api 
### POST Category
POST {{rootAPI}}/category
Content-Type: application/json


{
    "title": "Home Furniture"
}

### GET Categories
GET {{rootAPI}}/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2OTA2NzcxODQsImV4cCI6MTY5MDY3ODA4NH0.hzlnYlaj1EFU-g9ZTyYX1CyR_yVQmtEqVdh3kj5d_3I
 


 
# ====== request new  access jwt api



### GET Categories
GET {{rootAPI}}/admin/get-accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2OTA2ODgzOTAsImV4cCI6MTY5MzI4MDM5MH0.xNZBRHKYMLloGnYVoLyLp8ClPSPoUudLl8-ZNK-Nyvk
 

  
# ======  payment option


### post new po
POST {{rootAPI}}/payment-option
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2OTEyOTIzNzUsImV4cCI6MTY5MTI5MzI3NX0.YeKvegaNmZLMcJAkpquebjj-yxtE5L2QVE-22kWJIrk

{
    "status": "inactive",
    "title": "Pay by Bank Transfer",
    "description": "Please do EFT to the BSB: 123456, ACC: 23456787654. Thank you."
}

### get all po 
GET {{rootAPI}}/payment-option
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2OTEyOTMzMzMsImV4cCI6MTY5MTI5NDIzM30.6ct8PalzYK9M3Tz319uYvpRUT9rh0CLGmDCDTPWPR4w



# ======= product apis 

### get products
GET {{rootAPI}}/product